name: fudee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/resto.json
    - assets/bosscha.jpg
  fonts:
    - family: Jakarta
      fonts:
       - asset: assets/fonts/PlusJakartaSansRegular.ttf
       - asset: assets/fonts/PlusJakartaSansBold.ttf
         weight: 700
       - asset: assets/fonts/PlusJakartaSansExtraBold.ttf
         weight: 800
       - asset: assets/fonts/PlusJakartaSansSemiBold.ttf
         weight: 600
       - asset: assets/fonts/PlusJakartaSansItalic.ttf
         style: italic
